name: Deploy Databricks Asset Bundle

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: "Deploy to Databricks Workspace"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Deploy Bundle to Prod
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          databricks bundle deploy -t prod
